# fly.toml file generated for small-glitter-6 on 2023-01-23T14:02:09-04:00

app = "small-glitter-6"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

  PORT = "8080" # add this

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080 
  processes = ["app"]